spring:
  datasource:
    url: jdbc:log4jdbc:mysql://39.106.135.201:3306/crawl?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 8080

logging:
  pattern:
    level: info